In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
dataset=pd.read_csv('/content/Churn_Modelling.csv')

In [0]:
X=dataset.iloc[:,3:13].values

In [4]:
X


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
Y=dataset.iloc[:,13].values

In [6]:
Y

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
#Labelling is done to convert text into number
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])

In [8]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.compose import ColumnTransformer
# Country column
ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [10]:
X[:,1]


array([0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0], dtype=object)

In [0]:
X=X[:,1:]

In [12]:
X.shape

(10000, 11)

In [0]:
#Splitting the Dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [14]:
X_train

array([[0.0, 1.0, 667, ..., 1, 0, 163830.64],
       [1.0, 0.0, 427, ..., 1, 1, 57098.0],
       [0.0, 0.0, 535, ..., 1, 0, 185630.76],
       ...,
       [0.0, 0.0, 738, ..., 1, 0, 181429.87],
       [0.0, 1.0, 590, ..., 1, 1, 148750.16],
       [1.0, 0.0, 623, ..., 1, 0, 118855.26]], dtype=object)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
#Importing the Keras Libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [17]:
classifier=Sequential()

In [18]:
#Adding the Input Layer and the first Hidden Layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11))

In [0]:
#Adding the second Hidden Layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [0]:
#Adding the Output Layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))


In [21]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [22]:
classifier.fit(X_train,Y_train,batch_size=10,epochs=100)




Epoch 1/100





8000/8000 [==============================] - 12s 2ms/step - loss: 0.4852 - acc: 0.7952
Epoch 2/100
8000/8000 [==============================] - 3s 315us/step - loss: 0.4274 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 298us/step - loss: 0.4220 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 311us/step - loss: 0.4181 - acc: 0.8190
Epoch 5/100
8000/8000 [==============================] - 3s 313us/step - loss: 0.4158 - acc: 0.8292
Epoch 6/100
8000/8000 [==============================] - 3s 339us/step - loss: 0.4110 - acc: 0.8325
Epoch 7/100
8000/8000 [==============================] - 2s 309us/step - loss: 0.4069 - acc: 0.8336
Epoch 8/100
8000/8000 [==============================] - 3s 325us/step - loss: 0.4046 - acc: 0.8347
Epoch 9/100
8000/8000 [==============================] - 2s 307us/step - loss: 0.4028 - acc: 0.8340
Epoch 10/100
8000/8000 [==============================] - 2s 312us/step - loss: 0.4020 - acc:

In [0]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


In [24]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
#Using single observation to check the result
new_prediction=classifier.predict(sc.transform(np.array([[0.0,0,600,1,40,3,6000,2,1,1,5000]])))
new_prediction=(new_prediction>0.5)

In [26]:
new_prediction

array([[False]])